"""
Production settings: DEBUG off, host list and secret key validated.

Used automatically by wsgi.py / asgi.py. To exercise it locally:
    python manage.py runserver --settings=datapact_project.settings.production
"""

from django.core.exceptions import ImproperlyConfigured

from .base import *  # noqa: F401,F403

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

if not ALLOWED_HOSTS:  # noqa: F405
    raise ImproperlyConfigured(
        "ALLOWED_HOSTS is empty. Set ALLOWED_HOSTS in .env to a comma-separated "
        "list of host names this site is served from (see .env.example)."
    )

# Keys generated by `startproject` (including the key that shipped in the A1
# settings.py, now public in git history) start with this prefix, and the
# .env.example placeholder is public too. Production refuses all of them.
if SECRET_KEY.startswith('django-insecure-') or SECRET_KEY == 'replace-with-a-new-random-key':  # noqa: F405
    raise ImproperlyConfigured(
        "SECRET_KEY is a development/placeholder value. Generate a fresh key for "
        "production: python -c \"from django.core.management.utils import "
        "get_random_secret_key as g; print(g())\" and put it in .env."
    )

# HTTPS-only hardening (SECURE_SSL_REDIRECT, secure cookies, HSTS) is left off
# on purpose: it would break the plain-http local production-mode run that A2
# asks us to demonstrate. Enable it together with a real HTTPS deployment.
