# Generated by Django 5.2.17 on 2026-09-08 03:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('source_team', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=10)),
                ('change_note', models.CharField(blank=True, help_text="Why this version exists, e.g. 'Added AUDIT to allowed status values'.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='data_quality.dataset')),
            ],
            options={
                'ordering': ['dataset__name', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('NOT_NULL', 'Not null'), ('TYPE_MATCH', 'Type match'), ('RANGE', 'Range'), ('ALLOWED_VALUES', 'Allowed values'), ('REGEX', 'Format (regex)'), ('UNIQUE', 'Unique')], max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Type-specific arguments, e.g. {"min": 0, "max": 24}. Empty for NOT_NULL and UNIQUE.')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='data_quality.contract')),
            ],
            options={
                'ordering': ['column_name', 'rule_type'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('row_count', models.PositiveIntegerField(help_text='Number of data rows in the uploaded file.')),
                ('status', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('ERROR', 'Error')], max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='data_quality.contract')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_row_count', models.PositiveIntegerField()),
                ('sample_values', models.JSONField(blank=True, default=list, help_text='Examples of offending data, e.g. [{"row": 118, "value": "AUDIT"}].')),
                ('message', models.CharField(max_length=255)),
                ('resolution', models.CharField(choices=[('OPEN', 'Open'), ('DATA_ISSUE', 'Data issue'), ('CONTRACT_UPDATED', 'Contract updated')], default='OPEN', max_length=20)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='data_quality.validationrule')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='data_quality.validationrun')),
            ],
            options={
                'ordering': ['-failed_row_count'],
            },
        ),
        migrations.AddConstraint(
            model_name='dataset',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_dataset_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('dataset', 'version_number'), name='uniq_contract_dataset_version'),
        ),
        migrations.AddConstraint(
            model_name='violation',
            constraint=models.UniqueConstraint(fields=('run', 'rule'), name='uniq_violation_run_rule'),
        ),
    ]
